import type { AnalysisResult, TimelineEvent } from "@/lib/types";

const now = new Date().toISOString();

export const emptyAnalysis: AnalysisResult = {
  repo_id: "repository-ready",
  repo_url: "",
  analyzed_at: now,
  summary: {
    repo_id: "repository-ready",
    repo_url: "",
    name: "Repository ready",
    default_branch: null,
    description: "Enter a GitHub repository link to start progressive analysis.",
    languages: {},
    frameworks: [],
    entry_points: [],
    package_managers: [],
    important_files: [],
    folders: [],
    recommendations: [],
    confidence: "medium",
  },
  architecture: {
    summary: "The dashboard shell is ready. Repository roots, manifests, symbols, routes, and deep intelligence will stream in after analysis starts.",
    boundaries: [],
    nodes: [],
    edges: [],
    dependency_flow: [],
    confidence: "medium",
    framework_signals: [],
    graph_metrics: { analysis_phase: "idle", nodes: 0, edges: 0 },
    file_graph: {},
    risk_analysis: {},
    hotspots: [],
    topology: { analysis_phase: "idle" },
    evolution: {},
  },
  contributor_plan: {
    roadmap: [],
    beginner_files: [],
    recommended_tasks: [],
    good_first_issues: [],
    contribution_paths: [],
    learning_sequence: [],
    confidence: "medium",
  },
  intelligence: {
    complexity: {
      score: 0,
      level: "approachable",
      summary: "No repository has been analyzed yet.",
      drivers: [],
    },
    risks: [],
    ownership: [],
    dependency_insights: [],
    good_first_issues: [],
    contribution_paths: [],
    architecture_brief: "Start an analysis to load repository-specific intelligence.",
    demo_headline: "Repository analysis is ready to start.",
    confidence: "medium",
  },
  code_intelligence: {
    symbols: [],
    symbol_graph: {},
    routes: [],
    auth: {
      strategies: [],
      files: [],
      login_routes: [],
      token_issuers: [],
      validators: [],
      protected_routes: [],
      role_enforcement: [],
      session_persistence: [],
      explanation: "Analysis has not started yet.",
      confidence: "low",
    },
    state: {
      libraries: [],
      stores: [],
      providers: [],
      hooks: [],
      cache_layers: [],
      shared_state_boundaries: [],
      relationships: [],
      explanation: "Analysis has not started yet.",
      confidence: "low",
    },
    runtime: {},
    deployment: {},
    semantic_memory: [],
    retrieval_stats: { analysis_phase: "idle" },
    confidence: "low",
  },
  timeline: [],
  agent_manifest: {
    name: "codesherpa-ai",
    version: "0.1.0",
    skills: [],
    tools: [],
    workflow: {
      analysis_phase: "idle",
      cache_status: "none",
      deep_status: "idle",
      progressive_intelligence: true,
    },
    agents: [],
  },
};

export const demoTimeline: TimelineEvent[] = [
  {
    id: "demo-1",
    timestamp: now,
    agent: "GitAgent Runtime",
    title: "CodeSherpa GitAgent initialized",
    detail: "Loaded agent.yaml, SOUL.md, RULES.md, skills, tools, and workflow definitions.",
    status: "completed",
    confidence: "high",
  },
  {
    id: "demo-2",
    timestamp: now,
    agent: "Repository Analysis Agent",
    title: "Cloning repository",
    detail: "Repository materialized in the isolated analysis workspace. No project code was executed.",
    status: "completed",
    confidence: "high",
  },
  {
    id: "demo-3",
    timestamp: now,
    agent: "Repository Analysis Agent",
    title: "Detecting frameworks",
    detail: "Detected Next.js, React, TypeScript, Tailwind CSS, and Framer Motion from manifests.",
    status: "completed",
    confidence: "high",
  },
  {
    id: "demo-4",
    timestamp: now,
    agent: "Architecture Mapping Agent",
    title: "Building dependency graph",
    detail: "Generated architecture nodes for app, components, backend, services, docs, and tests.",
    status: "completed",
    confidence: "medium",
  },
  {
    id: "demo-5",
    timestamp: now,
    agent: "Onboarding Agent",
    title: "Generating onboarding guide",
    detail: "Created contributor roadmap, beginner files, and first task recommendations.",
    status: "completed",
    confidence: "high",
  },
];

export const demoAnalysis: AnalysisResult = {
  repo_id: "demo-codesherpa",
  repo_url: "https://github.com/user/repository",
  analyzed_at: now,
  summary: {
    repo_id: "demo-codesherpa",
    repo_url: "https://github.com/user/repository",
    name: "user/repository",
    default_branch: "canary",
    description:
      "A large TypeScript monorepo organized around framework packages, app examples, documentation, and test infrastructure.",
    languages: {
      TypeScript: 1840,
      JavaScript: 420,
      Markdown: 260,
      Rust: 48,
      CSS: 34,
    },
    frameworks: ["Next.js", "React", "TypeScript", "Turborepo", "Jest", "Playwright"],
    entry_points: ["packages/next/src/server/next.ts", "packages/next/src/client/index.ts", "test/e2e/app-dir"],
    package_managers: ["pnpm"],
    important_files: [
      {
        path: "package.json",
        role: "manifest",
        reason: "Workspace scripts and dependency manifest.",
        confidence: "high",
      },
      {
        path: "packages/next/package.json",
        role: "manifest",
        reason: "Core framework package manifest.",
        confidence: "high",
      },
      {
        path: "packages/next/src/server/next.ts",
        role: "entry",
        reason: "Server-side framework entry point.",
        confidence: "medium",
      },
      {
        path: "docs/01-app",
        role: "docs",
        reason: "App Router documentation area.",
        confidence: "medium",
      },
      {
        path: "test/e2e",
        role: "tests",
        reason: "End-to-end validation area.",
        confidence: "medium",
      },
    ],
    folders: [
      {
        path: "packages",
        role: "shared",
        description: "Core framework and package implementation area.",
        file_count: 970,
        confidence: "high",
      },
      {
        path: "test",
        role: "tests",
        description: "Validation suites and integration coverage.",
        file_count: 690,
        confidence: "high",
      },
      {
        path: "docs",
        role: "docs",
        description: "Documentation and learning material.",
        file_count: 300,
        confidence: "high",
      },
      {
        path: "examples",
        role: "frontend",
        description: "Framework usage examples and app templates.",
        file_count: 260,
        confidence: "medium",
      },
      {
        path: ".github",
        role: "infra",
        description: "CI, automation, and repository operations.",
        file_count: 44,
        confidence: "medium",
      },
    ],
    recommendations: [
      "Start architecture review from packages/next and follow server/client boundaries.",
      "Use tests under test/e2e to understand supported behavior before making changes.",
      "Read docs/01-app when exploring App Router concepts.",
    ],
    confidence: "high",
  },
  architecture: {
    summary:
      "The repository behaves like a framework monorepo: packages contains product implementation, docs explains supported usage, examples demonstrates integration paths, and tests validates behavior across routing and runtime surfaces.",
    boundaries: [
      "Core framework boundary appears under packages/next.",
      "Documentation and examples are separate learning and validation surfaces.",
      "Test infrastructure is a major subsystem and should be treated as part of architecture.",
    ],
    nodes: [
      {
        id: "packages",
        label: "packages",
        type: "shared",
        description: "Core framework packages and reusable internals.",
        confidence: "high",
        role: "framework internals",
        framework: "Next.js",
        dependency_count: 38,
        ownership_score: 0.92,
        runtime_classification: "library",
        group: "shared",
        x: 42,
        y: 34,
        metadata: { file_count: 970, signals: ["workspace package imports", "server/client runtime entrypoints"] },
      },
      {
        id: "docs",
        label: "docs",
        type: "docs",
        description: "Product documentation and onboarding material.",
        confidence: "high",
        role: "documentation",
        dependency_count: 7,
        ownership_score: 0.42,
        runtime_classification: "knowledge",
        group: "docs",
        x: 12,
        y: 24,
        metadata: { file_count: 300, signals: ["docs reference examples and package APIs"] },
      },
      {
        id: "examples",
        label: "examples",
        type: "frontend",
        description: "Runnable app examples.",
        confidence: "medium",
        role: "frontend examples",
        framework: "Next.js",
        entrypoint: true,
        dependency_count: 18,
        ownership_score: 0.58,
        runtime_classification: "client/runtime",
        group: "frontend",
        x: 18,
        y: 58,
        metadata: { file_count: 260, signals: ["App Router examples", "public asset references"] },
      },
      {
        id: "test",
        label: "test",
        type: "tests",
        description: "End-to-end and integration validation.",
        confidence: "high",
        role: "test suite",
        dependency_count: 21,
        ownership_score: 0.7,
        runtime_classification: "validation",
        group: "testing",
        x: 30,
        y: 82,
        metadata: { file_count: 690, signals: ["e2e imports runtime packages"] },
      },
      {
        id: "manifest",
        label: "manifests",
        type: "config",
        description: "Workspace dependency and runtime configuration.",
        confidence: "high",
        role: "dependency manifest",
        dependency_count: 16,
        ownership_score: 0.36,
        runtime_classification: "configuration",
        group: "infrastructure",
        x: 78,
        y: 20,
        metadata: { file_count: 8, signals: ["package.json", "pnpm-workspace.yaml", "tsconfig.json"] },
      },
      {
        id: ".github",
        label: ".github",
        type: "infra",
        description: "CI and automation workflows.",
        confidence: "medium",
        role: "deployment config",
        dependency_count: 9,
        ownership_score: 0.32,
        runtime_classification: "deployment",
        group: "infrastructure",
        x: 82,
        y: 64,
        metadata: { file_count: 44, signals: ["GitHub Actions workflows run tests and release checks"] },
      },
    ],
    edges: [
      { source: "manifest", target: "packages", label: "configures", confidence: "high", weight: 6, kind: "manifest", reasons: ["Workspace manifests configure package boundaries"] },
      { source: "packages", target: "examples", label: "imports (12)", confidence: "high", weight: 12, kind: "import", reasons: ["Examples import framework package APIs"] },
      { source: "docs", target: "examples", label: "explains", confidence: "medium", weight: 3, kind: "semantic", reasons: ["Docs reference runnable examples"] },
      { source: "test", target: "packages", label: "validates (18)", confidence: "high", weight: 18, kind: "import", reasons: ["Tests import runtime packages and fixtures"] },
      { source: ".github", target: "test", label: "runs", confidence: "medium", weight: 4, kind: "deployment", reasons: ["GitHub Actions run test jobs"] },
    ],
    dependency_flow: [
      "Workspace dependencies enter through package manifests and pnpm.",
      "Core runtime exploration should start in packages/next.",
      "Examples and tests reveal supported product behavior.",
    ],
    confidence: "high",
    framework_signals: ["Next.js: package manifest/config signal", "React: package manifest/config signal", "Playwright: test dependency signal"],
    graph_metrics: {
      source_files_analyzed: 2500,
      imports_detected: 8400,
      imports_resolved: 3100,
      nodes: 6,
      edges: 5,
      connected_ratio: 1,
      import_trace_density: 1.24,
    },
  },
  contributor_plan: {
    roadmap: [
      {
        title: "Read the repository contract",
        description: "Scan package manifests and top-level docs to understand workspace boundaries.",
        files: ["package.json", "pnpm-workspace.yaml"],
        difficulty: "easy",
        estimate: "20 min",
      },
      {
        title: "Trace the framework core",
        description: "Open packages/next and follow server and client entry points.",
        files: ["packages/next/package.json", "packages/next/src/server/next.ts"],
        difficulty: "medium",
        estimate: "45 min",
      },
      {
        title: "Use tests as behavior maps",
        description: "Pick an e2e test matching the feature area before editing internals.",
        files: ["test/e2e"],
        difficulty: "medium",
        estimate: "60 min",
      },
      {
        title: "Make a scoped contribution",
        description: "Start with docs, examples, tests, or localized fixes before changing framework internals.",
        files: ["docs", "examples", "test/e2e"],
        difficulty: "easy",
        estimate: "1-2 hr",
      },
    ],
    beginner_files: [
      {
        path: "package.json",
        role: "manifest",
        reason: "Workspace scripts and dependency map.",
        confidence: "high",
      },
      {
        path: "docs",
        role: "docs",
        reason: "Best learning surface for framework concepts.",
        confidence: "high",
      },
      {
        path: "examples",
        role: "frontend",
        reason: "Runnable usage patterns.",
        confidence: "medium",
      },
    ],
    recommended_tasks: [
      {
        title: "Improve a docs example",
        why: "High value and low architectural risk.",
        files: ["docs", "examples"],
        difficulty: "easy",
      },
      {
        title: "Add a focused regression test",
        why: "Tests teach behavior and create reviewable scope.",
        files: ["test/e2e"],
        difficulty: "medium",
      },
      {
        title: "Document one internal path",
        why: "A short architecture note helps future contributors.",
        files: ["packages/next/src/server/next.ts"],
        difficulty: "medium",
      },
    ],
    good_first_issues: [
      {
        title: "Add a contributor quickstart for App Router internals",
        rationale: "A compact guide can connect docs, examples, and the core package without requiring risky source changes.",
        files: ["docs", "examples", "packages/next/src/server/next.ts"],
        labels: ["good first issue", "documentation", "onboarding"],
        difficulty: "easy",
        estimated_time: "45-90 min",
        confidence: "high",
      },
      {
        title: "Document one server runtime path",
        rationale: "The architecture map identifies server entry points that would benefit from an evidence-backed explanation.",
        files: ["packages/next/src/server/next.ts", "packages/next/package.json"],
        labels: ["good first issue", "architecture"],
        difficulty: "medium",
        estimated_time: "1-2 hr",
        confidence: "medium",
      },
      {
        title: "Add a focused regression test for an example route",
        rationale: "A test-first contribution teaches behavior and stays scoped to an observable app path.",
        files: ["test/e2e", "examples"],
        labels: ["good first issue", "tests"],
        difficulty: "medium",
        estimated_time: "1-2 hr",
        confidence: "medium",
      },
    ],
    contribution_paths: [
      {
        name: "Docs-first contributor",
        outcome: "Ship a helpful docs/example improvement with low architectural risk.",
        steps: ["Read package manifests", "Choose one confusing docs path", "Improve the explanation", "Validate links and example references"],
        files: ["docs", "examples", "package.json"],
        difficulty: "easy",
      },
      {
        name: "Behavior-first contributor",
        outcome: "Trace one runtime behavior and add a focused regression test.",
        steps: ["Start at packages/next", "Find matching e2e coverage", "Add one assertion", "Run the local test target"],
        files: ["packages/next/src/server/next.ts", "test/e2e"],
        difficulty: "medium",
      },
      {
        name: "Core-package contributor",
        outcome: "Make a localized change inside the framework package after mapping ownership boundaries.",
        steps: ["Pick one package area", "Read neighboring tests", "Avoid cross-package churn", "Keep the pull request scoped"],
        files: ["packages/next", "test/e2e"],
        difficulty: "medium",
      },
    ],
    learning_sequence: ["Purpose", "Manifests", "Core package", "Examples", "Tests", "First scoped PR"],
    confidence: "high",
  },
  intelligence: {
    complexity: {
      score: 86,
      level: "advanced",
      summary:
        "This repository is advanced: contributors should use docs, examples, and tests as maps before changing framework internals.",
      drivers: ["large monorepo", "multiple language families", "framework package internals", "heavy test surface"],
    },
    risks: [
      {
        title: "High framework surface area",
        severity: "low",
        evidence: ["Next.js", "React", "TypeScript", "Jest", "Playwright"],
        recommendation: "Document contribution paths by subsystem so newcomers avoid cross-cutting changes.",
        confidence: "medium",
      },
      {
        title: "Core package changes are high blast-radius",
        severity: "medium",
        evidence: ["packages/next", "test/e2e"],
        recommendation: "Require tests or examples for behavior changes touching runtime internals.",
        confidence: "medium",
      },
      {
        title: "Contributor surface is broad",
        severity: "low",
        evidence: ["docs", "examples", "packages", "test"],
        recommendation: "Route new contributors toward docs, examples, or focused tests first.",
        confidence: "high",
      },
    ],
    ownership: [
      {
        area: "Core platform",
        owner_hint: "Likely owned by the team closest to packages/next.",
        paths: ["packages"],
        responsibilities: ["framework internals", "runtime behavior", "package boundaries"],
        confidence: "high",
      },
      {
        area: "Developer education",
        owner_hint: "Likely owned by maintainers closest to docs and examples.",
        paths: ["docs", "examples"],
        responsibilities: ["onboarding", "guides", "examples"],
        confidence: "high",
      },
      {
        area: "Quality and regression",
        owner_hint: "Likely owned by maintainers closest to test/e2e.",
        paths: ["test"],
        responsibilities: ["test coverage", "fixtures", "release confidence"],
        confidence: "high",
      },
      {
        area: "Operations",
        owner_hint: "Likely owned by maintainers closest to .github workflows.",
        paths: [".github"],
        responsibilities: ["CI", "release automation", "repository operations"],
        confidence: "medium",
      },
    ],
    dependency_insights: [
      {
        ecosystem: "JavaScript",
        signal: "Workspace dependencies declared through package manifests",
        dependencies: ["next", "react", "typescript", "jest", "playwright"],
        risk: "low",
        recommendation: "Review workspace package boundaries and lockfile before making runtime changes.",
      },
      {
        ecosystem: "Rust",
        signal: "Rust package signals appear in the toolchain surface",
        dependencies: [],
        risk: "low",
        recommendation: "Treat native compiler/runtime pieces as advanced contribution areas.",
      },
    ],
    good_first_issues: [
      {
        title: "Add a contributor quickstart for App Router internals",
        rationale: "A compact guide can connect docs, examples, and the core package without requiring risky source changes.",
        files: ["docs", "examples", "packages/next/src/server/next.ts"],
        labels: ["good first issue", "documentation", "onboarding"],
        difficulty: "easy",
        estimated_time: "45-90 min",
        confidence: "high",
      },
      {
        title: "Document one server runtime path",
        rationale: "The architecture map identifies server entry points that would benefit from an evidence-backed explanation.",
        files: ["packages/next/src/server/next.ts", "packages/next/package.json"],
        labels: ["good first issue", "architecture"],
        difficulty: "medium",
        estimated_time: "1-2 hr",
        confidence: "medium",
      },
    ],
    contribution_paths: [
      {
        name: "Docs-first contributor",
        outcome: "Ship a helpful docs/example improvement with low architectural risk.",
        steps: ["Read package manifests", "Choose one confusing docs path", "Improve the explanation", "Validate links and example references"],
        files: ["docs", "examples", "package.json"],
        difficulty: "easy",
      },
      {
        name: "Behavior-first contributor",
        outcome: "Trace one runtime behavior and add a focused regression test.",
        steps: ["Start at packages/next", "Find matching e2e coverage", "Add one assertion", "Run the local test target"],
        files: ["packages/next/src/server/next.ts", "test/e2e"],
        difficulty: "medium",
      },
    ],
    architecture_brief:
      "user/repository is best explained as a framework monorepo with core packages, documentation, examples, and high-signal tests.",
    demo_headline: "Mapped user/repository into framework internals, documentation surfaces, tests, and contributor paths.",
    confidence: "high",
  },
  code_intelligence: {
    symbols: [
      {
        id: "packages/next/src/server/next.ts::NextServer:1",
        name: "NextServer",
        type: "service",
        file: "packages/next/src/server/next.ts",
        line: 1,
        language: "TypeScript",
        runtime_role: "backend runtime",
        signature: "class NextServer",
        imports: [],
        used_by: [],
        calls: [],
        decorators: [],
      },
    ],
    symbol_graph: { nodes: 1, edges: [] },
    routes: [],
    auth: {
      strategies: [],
      files: [],
      login_routes: [],
      token_issuers: [],
      validators: [],
      protected_routes: [],
      role_enforcement: [],
      session_persistence: [],
      explanation: "No explicit authentication flow was detected from demo memory.",
      confidence: "low",
    },
    state: {
      libraries: [],
      stores: [],
      providers: [],
      hooks: [],
      cache_layers: [],
      shared_state_boundaries: [],
      relationships: [],
      explanation: "No explicit frontend state layer is included in the demo memory.",
      confidence: "low",
    },
    runtime: {
      entry_points: ["packages/next/src/server/next.ts", "packages/next/src/client/index.ts"],
      route_count: 0,
      frameworks: ["Next.js", "React"],
    },
    deployment: {
      files: [".github/workflows"],
      targets: ["GitHub Actions"],
      manifests: {},
    },
    semantic_memory: [
      {
        id: "demo-runtime",
        type: "architecture",
        title: "Runtime architecture",
        file: "packages/next/src/server/next.ts",
        summary: "Demo memory maps the Next.js server and client package entrypoints as runtime starting points.",
        keywords: ["runtime", "architecture", "server", "client", "next"],
        importance: 8,
        relations: ["packages/next/src/server/next.ts::NextServer:1"],
      },
    ],
    retrieval_stats: {
      source_files_analyzed: 0,
      symbols_indexed: 1,
      routes_indexed: 0,
      memory_items: 1,
      engine: "demo",
    },
    confidence: "medium",
  },
  timeline: demoTimeline,
  agent_manifest: {
    name: "codesherpa-ai",
    version: "0.1.0",
    skills: ["repository-analysis", "architecture-mapping", "onboarding", "issue-debugging", "documentation"],
    tools: ["cli", "read", "memory", "repo_clone", "repo_scan", "dependency_graph"],
    workflow: { default: "repository-understanding" },
    agents: ["repository_analysis", "architecture_mapping", "onboarding", "issue_debugging", "documentation"],
  },
};
